# -*- coding: utf-8 -*-
"""
Tests dump functionality
"""
import json
import os
import tempfile

import pytest
import pandas as pd

from cognita_client.wrap.load import load_model

from image_classifier.classify_image import keras_evaluate

_DATA_PATH =  os.path.join(os.path.dirname(os.path.abspath(__file__)), '../../data/') # /a/b/c/d/e
_EXPECTED_CLASSES = {'elephant.jpg':'xcv', 'model-t.jpg':'xcv', 'cropped_panda.jpg':'xvc'}
_LABEL_FILE = 'keras_class_names.txt'


def test_image_classify_keras():
    '''Tests dumping with image classifier'''
    assert os.path.exists(_DATA_PATH)  # must have image test path
    target_model = None

    with tempfile.TemporaryDirectory() as tdir:
        #tdir = os.path.join(_DATA_PATH, 'test')

        for fileKey in _EXPECTED_CLASSES:
            train_path = os.path.join(_DATA_PATH, fileKey)
            assert os.path.isfile(train_path), "File: {:} not found".format(train_path) # must have image test path
            if False : #target_model is None:
                label_path = os.path.join(_DATA_PATH, _LABEL_FILE)
                assert os.path.isfile(label_path), "Label file: {:} not found".format(label_path) # must have image test path

                # this is one-time training to build and serialize the model
                keras_evaluate({'image': train_path, 'model_path': '', 'dump_model': tdir, 'label_path': label_path,
                                'num_top_predictions': 5})

            target_model = load_model(tdir)  # refers to ./model dir in pwd. generated by helper script also in this dir
            assert hasattr(target_model, 'transform')

            binStream = open(train_path, 'rb').read()
            X = pd.DataFrame([['image/jpeg', binStream]], columns=['mime_type', 'binary_stream'])
            resp = target_model.transform.from_native(X)
            pred = resp.as_native()

            outC = os.path.join(tdir, "{}.class.csv".format(fileKey))
            pred.to_csv(outC)
            print("{:} -> {:}".format(train_path, pred))


if __name__ == '__main__':
    '''Test area'''
    pytest.main([__file__, ])
